# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseUIAPP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseUIAPP
  pod 'FirebaseUI/Auth'
  # Googleログイン
  pod 'FirebaseUI/Google'
  # Facebookログイン
  #pod 'FirebaseUI/Facebook'
  # Sign in with Apple, Twitterなど
  pod 'FirebaseUI/OAuth'
  # 電話番号
  #pod 'FirebaseUI/Phone'

end
